### ISSUE TITLE
Use new options format

### ISSUE THREAD

**Issue by sekrett** [sous-chefs/freebsd#28]
1. Instead of:
   `WITH_APACHE=true` and `WITHOUT_APACHE=true`
   it should be:
   `OPTIONS_FILE_SET+=APACHE` and `OPTIONS_FILE_UNSET+=APACHE`
2. Cookbook should merge old options and convert correctly.
3. The head should be added:
   
   <pre># Options for php56-5.6.19
   _OPTIONS_READ=php56-5.6.19
   _FILE_COMPLETE_OPTIONS_LIST=CLI CGI FPM EMBED PHPDBG DEBUG DTRACE IPV6 MAILHEAD LINKTHR ZTS</pre>

I will try to implement this.

**Comment by sekrett** [comment]
Implemented in v0.7.0. Not converting old options, not needed, because FreeBSD also ignores old WITH/WITHOUT.

**Comment by martinisoft** [comment]
I commented on the pull request @sekrett as it looks like we didn't get around to the code review and it has a few conflicts along with needing to comply with the DCO. Once that has been updated we'll take a look and thank you for sending the contribution. 👍
