### ISSUE TITLE
The meaning of this cookbook

### ISSUE THREAD

**Issue by sekrett** [sous-chefs/freebsd#35]
@tas50 Hello again.

I wonder why you have converted `port_options` to a custom resource after you say this should be moved to Chef core and I agree. This code is broken, useless. I can update the format of generated options file but you don't accept my patches.

Now I really don't understand why this cookbook should exist at all. Only for `portsnap` updates? It's like creating a Debian cookbook which performs only `apt-get update`. Really, does it make sense? Is it possible to deprecate this cookbook and move everything to Chef core (client)?

**Comment by cheeseplus** [comment]
The pattern of proving out resources in cookbooks before moving them to core is fairly tried and true in the ecosystem. The example used of Debian cookbook only doing apt-update is exactly what we had in the ecosystem before `apt_update` was added in core. Generally speaking a Resource is a resource regardless of whether it's in core or a cookbook - chef itself doesn't really care.

That said, there are TONS of resources out there and prioritizing these is huge task for an already overloaded team. This is to say, it's entirely possible to migrate these things to core chef but it's a matter of priority, resourcing, and/or someone doing the PR against chef/chef.
